apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-api-deployment
  labels:
    app: node-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-api
  template:
    metadata:
      labels:
        app: node-api
    spec:
      containers:
      - name: node-api
        image: taugem/nodeapi:v0.1
        ports:
        - containerPort: 5041
        resources:
          requests:
            memory: "32M"
            cpu: "250m"
          limits:
            memory: "64M"
            cpu: "500m"          

---

apiVersion: v1
kind: Service
metadata:
  name: node-api-service
  labels:
    app: node-api
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 5041
  selector:
    app: node-api
  type: ClusterIP
status:
    loadBalancer: {}

# ---

# apiVersion: autoscaling/v1
# kind: HorizontalPodAutoscaler
# metadata:
#   name: node-api-hpa
# spec:
#   maxReplicas: 4  
#   minReplicas: 1   
#   scaleTargetRef:
#     apiVersion: apps/v1
#     kind: Deployment
#     name: node-api-deployment
#   targetCPUUtilizationPercentage: 80