apiVersion: apps/v1
kind: Deployment
metadata:
  name: warp-api-deployment
  labels:
    app: warp-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: warp-api
  template:
    metadata:
      labels:
        app: warp-api
    spec:
      containers:
      - name: warp-api
        image: taugem/warpapi:v0.1
        ports:
        - containerPort: 5041
        resources:
          requests:
            memory: "32M"
            cpu: "250m"
          limits:
            memory: "64M"
            cpu: "500m"      
          # requests:
          #   memory: "8M"
          #   cpu: "50m"
          # limits:
          #   memory: "16M"
          #   cpu: "100m"        
---

apiVersion: v1
kind: Service
metadata:
  name: warp-api-service
  labels:
    app: warp-api
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 5041
  selector:
    app: warp-api
  type: ClusterIP
status:
    loadBalancer: {}

# ---

# apiVersion: autoscaling/v1
# kind: HorizontalPodAutoscaler
# metadata:
#   name: warp-api-hpa
# spec:
#   maxReplicas: 4  
#   minReplicas: 1   
#   scaleTargetRef:
#     apiVersion: apps/v1
#     kind: Deployment
#     name: warp-api-deployment
#   targetCPUUtilizationPercentage: 80
