apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-api-deployment
  labels:
    app: spring-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-api
  template:
    metadata:
      labels:
        app: spring-api
    spec:
      containers:
      - name: spring-api
        image: taugem/springapi:v0.1
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "32M"
            cpu: "250m"
          limits:
            memory: "56M"
            cpu: "500m"          

---

apiVersion: v1
kind: Service
metadata:
  name: spring-api-service
  labels:
    app: spring-api
spec:
  type: ClusterIP
  selector:
    app: spring-api
  ports:
  - name: http
    port: 5041

---

apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: spring-api-hpa
spec:
  maxReplicas: 4  
  minReplicas: 1   
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: spring-api-deployment
  targetCPUUtilizationPercentage: 80